name: Docker CI

on:
  push:
    branches: [ main ]
  #schedule:
    #- cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    - name: Checkout upstream
      uses: actions/checkout@v2
      with:
        repository: sapcc/mosquitto-exporter
        path: upstream

    - name: Login to Github registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - id: upstream_release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: sapcc
        repo: mosquitto-exporter
        excludes: prerelease, draft

    - id: release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: niwla23
        repo: mosquitto-exporter-crossplatform
        excludes: prerelease, draft

    - run: echo ${{steps.upstream_release.outputs.release}}
    - run: echo ${{steps.release.outputs.release}}

    - name: Set up QEMU
      if: steps.upstream_release.outputs.release != steps.release.outputs.release
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      if: steps.upstream_release.outputs.release != steps.release.outputs.release
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      if: steps.upstream_release.outputs.release != steps.release.outputs.release
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        context: ./upstream
        file: upstream/Dockerfile
        push: true
        tags: ghcr.io/niwla23/mosquitto-exporter-crossplatform:latest,ghcr.io/niwla23/mosquitto-exporter-crossplatform:${{steps.upstream_release.outputs.release}}

    - name: Create a Release
      if: steps.upstream_release.outputs.release != steps.release.outputs.release
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: ${{steps.upstream_release.outputs.release}}
